# DigitalOcean App Platform spec for Cloud Pirates
# Replace <YOUR_GITHUB_REPO> with "owner/repo" if deploying from GitHub,
# or remove the github block and deploy from local source using doctl.

name: cloud-pirates
region: nyc

services:
  - name: web
    github:
      repo: <YOUR_GITHUB_REPO>
      branch: main
    run_command: "node backend/index.js"
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DATABASE_URL
      - key: SPACES_ENDPOINT
      - key: SPACES_KEY
      - key: SPACES_SECRET
      - key: SPACES_BUCKET
      - key: INFERENCE_URL
      - key: NODE_ENV

  - name: worker
    github:
      repo: <YOUR_GITHUB_REPO>
      branch: main
    run_command: "node backend/worker.js"
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DATABASE_URL
      - key: REDIS_URL
      - key: SPACES_ENDPOINT
      - key: SPACES_KEY
      - key: SPACES_SECRET
      - key: SPACES_BUCKET
      - key: INFERENCE_URL

# You can also declare databases and other resources here if you have them managed in DigitalOcean.
# For local testing you can omit the github sections and deploy from local with doctl.
