apiVersion: v1
kind: Service
metadata:
  name: pirates-frontend
  namespace: cloud-pirates
spec:
  type: LoadBalancer
  selector:
    app: pirates-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
